# Generated by Django 5.1.5 on 2025-02-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0005_alter_employee_hire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_manager',
            name='task_status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Not Started', 'Not Started')], max_length=15),
        ),
    ]
