# Generated by Django 5.1.5 on 2025-02-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0006_alter_task_manager_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_manager',
            name='task_priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10),
        ),
        migrations.AlterField(
            model_name='task_manager',
            name='task_status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Completed', 'Completed'), ('In Progress', 'In Progress')], max_length=15),
        ),
    ]
