# Generated by Django 5.1.5 on 2025-02-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0007_alter_task_manager_task_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_manager',
            name='task_priority',
            field=models.CharField(choices=[('Medium', 'Medium'), ('Low', 'Low'), ('High', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='task_manager',
            name='task_status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Not Started', 'Not Started')], max_length=15),
        ),
    ]
