# Generated by Django 5.1.5 on 2025-02-25 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0008_alter_task_manager_task_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_manager',
            name='task_status',
        ),
        migrations.AlterField(
            model_name='task_manager',
            name='task_priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10),
        ),
        migrations.CreateModel(
            name='Task_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=15)),
                ('file', models.FileField(blank=True, null=True, upload_to='task_files/')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_task', to='emp_app.task_manager')),
            ],
        ),
    ]
