# Generated by Django 5.1.5 on 2025-02-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0014_dailyupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyupdate',
            name='weekly_hours',
        ),
    ]
