# Generated by Django 5.1.5 on 2025-03-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0016_employee_date_of_birth_employee_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
